parameters:
    database_driver:
    database_host:    
    database_port:     ~
    database_name:     
    database_user:     
    database_password: 

    mailer_transport:  smtp
    mailer_host:       127.0.0.1
    mailer_user:       ~
    mailer_password:   ~

    locale:            en
    secret:            ThisTokenIsNotSoSecretChangeIt
    
    public_app_url:   
    scripts:                     
    web_folder_videos_root:      
    video_renderer_config_path:  
