jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        FOS\UserBundle\Model\UserInterface: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        #wsse_secured:
        #    pattern: ^/api/.*
        #    stateless: true
        #    wsse:      true
        #    anonymous : true
        #    wsse: { lifetime: 30}
            
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        
        #admin:
        #    pattern:        ^/admin
        #    switch_user:    true
        #    form_login:
        #        provider:   fos_userbundle
        #        csrf_provider: form.csrf_provider
        #        login_path: fos_user_security_login
        #        check_path: fos_user_security_check
        #        default_target_path: /admin/home
        #    logout:         
        #        path:   fos_user_security_logout
        #        target: fos_user_security_login
        #    anonymous:      false
            
        main:
            pattern:        ^/
            switch_user:    true
            anonymous:      ~
            form_login:
                provider:   fos_userbundle
                csrf_provider: form.csrf_provider
                login_path: /login
                default_target_path: admin_dashboard
                 
            logout:         
                path:   /logout
                target: /login
            anonymous:      true

       
            
    access_control:
        - { path: ^/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/profile, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/*, role: IS_AUTHENTICATED_REMEMBERED }
        - { path: ^/, role: IS_AUTHENTICATED_ANONYMOUSLY }